spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mdb1.cmgya1upayhs.ap-northeast-2.rds.amazonaws.com:3306/test
    username: root
    password: rootroot
  data:
    elasticsearch:
      cluster-nodes: 15.164.189.220:9200
      username: uwho
      password: Uwho1234!
      rest:
        client:
          sniffer.enabled: true
          sniff-after-connect-failure: true
          sniff-interval: 30000
api:
  tmdb:
    key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0OWJjZmNhOWZkNWY0NGQyMjZhYzgzMTU5NzZhY2ZkYyIsInN1YiI6IjY1MWUzMmE0M2QzNTU3MDExY2ZmZThhYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-uufjYqYRvt2OC66c1euvWmZdEOGy-gGvmRoQ1fP2AA

server:
  port: 8080
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: uwhoo1234!
    key-alias: spring
