spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mdb1.cmgya1upayhs.ap-northeast-2.rds.amazonaws.com:3306/test
    username: root
    password: rootroot
    hikari:
      maximum-pool-size: 2
  jackson:
    time-zone: Asia/Seoul
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    serialize-nulls: true

login:
  registration:
    google:
      client-id: 866692341598-2ng40irpued2c75s4vnt3cnrljc8oh9k.apps.googleusercontent.com
#      redirect-uri: http://localhost:8080/api/login/oauth2/code/google
      client-secret: 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
      scope:
        - email
        - profile
    kakao:
      client-id: 5226f263acf8306b81d4c11afbb2afc2
#      redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
      client-name: kakao
      client-authentication-method: POST
      authorization-grant-type: authorization_code
      scope:
        - account_email
        - profile_image
        - profile_nickname
    naver:
      client-id: 8B0WOI_5YTPZcSr_9haJ
      client-secret: eo89L4YJJw
      client-name: naver
#      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      authorization-grant-type: authorization_code
      scope:
        - id
        - nickname
        - name
        - profile_image
  provider:
    google:
      user-info-uri: https://www.googleapis.com/userinfo/v2/me
      user-name-attribute: id
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: id
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response

api:
  tmdb:
    key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0OWJjZmNhOWZkNWY0NGQyMjZhYzgzMTU5NzZhY2ZkYyIsInN1YiI6IjY1MWUzMmE0M2QzNTU3MDExY2ZmZThhYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-uufjYqYRvt2OC66c1euvWmZdEOGy-gGvmRoQ1fP2AA

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 24h
#  ssl:
#    key-store: /home/ubuntu/app/BE/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: uwhoo1234!
#    key-alias: spring
logging:
  config: classpath:logback-local.xml