name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - feature/frontend-main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build React app
        run: npm run build
      
      - name: Firebase login
        run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"
      
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
